VIN=$CAR_VIN
PRIVATE_KEY=$CAR_PRIVATE_KEY
HCI_NUM=$BLE_HCI_NUM
BLE_CMD_TIMEOUT=$BLE_COMMAND_TIMEOUT
BLE_CONN_TIMEOUT=$BLE_CONNECT_TIMEOUT
BIN_PATH=/root/go/bin/
SCRIPTS_PATH=/root/go/bin/tesla-ble/
COMMAND_TIMEOUT=55
